name: eCommerce-microservices

services:
  postgresql:
    image: postgres:17.4-alpine
    container_name: docker-postgresql
    restart: always
    environment:
      POSTGRES_USER: ultrasur
      POSTGRES_PASSWORD: ultrasur123
      POSTGRES_DB: user_services
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: docker-pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nanasuryana335@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ultrasur123
    volumes:
      - pgadmin-vol:/var/lib/pgadmin/data
  redis:
    image: redis:alpine
    container_name: docker-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-vol:/var/lib/redis/data

volumes:
  postgres-vol:
  pgadmin-vol:
  redis-vol:
