app:
  port: 6969

database:
  host: localhost
  user: ultrasur
  password: ultrasur123
  name: user_services
  port: 5432

redis:
  host: localhost
  port: 6379
  password:

secret:
  jwt_secret: j3w3t353cr3t